(function() {var implementors = {};
implementors['tokei'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='tokei/enum.LanguageType.html' title='tokei::LanguageType'>LanguageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tokei/struct.Stats.html' title='tokei::Stats'>Stats</a>",];implementors['tokei'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='tokei/enum.LanguageType.html' title='tokei::LanguageType'>LanguageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tokei/struct.Stats.html' title='tokei::Stats'>Stats</a>",];implementors['tokei'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='tokei/enum.LanguageType.html' title='tokei::LanguageType'>LanguageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tokei/struct.Stats.html' title='tokei::Stats'>Stats</a>",];implementors['tokei'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='tokei/enum.LanguageType.html' title='tokei::LanguageType'>LanguageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tokei/struct.Stats.html' title='tokei::Stats'>Stats</a>",];implementors['tokei'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='tokei/enum.LanguageType.html' title='tokei::LanguageType'>LanguageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tokei/struct.Stats.html' title='tokei::Stats'>Stats</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
